import json
import os
from pathlib import Path
from datetime import datetime

class BackupService:
    def __init__(self):
        self.data_dir = Path(__file__).resolve().parent.parent.parent / "data"
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self.backup_file = self.data_dir / "database_backup.json"

    def backup_to_json(self):
        """
        Dumps the entire 'messages' and 'user_continuity' tables to a JSON file.
        This provides a real-time shadow copy.
        """
        try:
            from app.db import get_db_connection
            conn = get_db_connection()
            cursor = conn.cursor()
            
            # Export Sessions
            cursor.execute("SELECT id, title, created_at, updated_at FROM sessions ORDER BY created_at ASC")
            sessions = [dict(row) for row in cursor.fetchall()]

            # Export Messages
            cursor.execute("SELECT id, session_id, role, content, created_at, session_active, feedback FROM messages ORDER BY id ASC")
            messages = [dict(row) for row in cursor.fetchall()]
            
            # Export Message Embeddings
            # Note: We don't backup embeddings directly as they are extremely large and can be 
            # easily regenerated by backfill_embeddings.py if restored, but we will back them up 
            # as lists of floats to ensure perfect restoration if needed.
            cursor.execute("SELECT message_id, embedding::text, created_at FROM message_embeddings")
            embeddings = [dict(row) for row in cursor.fetchall()]
            
            # Export User Continuity
            cursor.execute("SELECT identity, type, content, importance, priority, retired, created_at, last_updated FROM user_continuity")
            continuity = [dict(row) for row in cursor.fetchall()]
            
            cursor.close()
            conn.close()
            
            backup_data = {
                "timestamp": datetime.now().isoformat(),
                "sessions": sessions,
                "messages": messages,
                "message_embeddings": embeddings,
                "user_continuity": continuity
            }
            
            # Write to temporary file first to prevent corruption if interrupted
            temp_file = self.backup_file.with_suffix(".tmp")
            with open(temp_file, "w", encoding="utf-8") as f:
                json.dump(backup_data, f, indent=2)
                
            # Atomic rename
            temp_file.replace(self.backup_file)
            print(f"Successfully backed up {len(messages)} messages and {len(continuity)} continuity items to {self.backup_file.name}")
            
        except Exception as e:
            print(f"Failed to run automated backup: {e}")

    def restore_from_json(self) -> bool:
        """
        Restores the database from the JSON backup.
        Only runs if the database is confirmed to be empty to prevent overwrites.
        """
        if not self.backup_file.exists():
            print("No backup file found. Starting fresh.")
            return False
            
        try:
            with open(self.backup_file, "r", encoding="utf-8") as f:
                backup_data = json.load(f)
                
            from app.db import get_db_connection
            conn = get_db_connection()
            cursor = conn.cursor()
            
            # Safety check: Ensure DB is empty
            cursor.execute("SELECT COUNT(*) FROM messages")
            if cursor.fetchone()[0] > 0:
                print("Database is not empty. Aborting auto-restore.")
                return False
                
            sessions = backup_data.get("sessions", [])
            messages = backup_data.get("messages", [])
            embeddings = backup_data.get("message_embeddings", [])
            continuity = backup_data.get("user_continuity", [])
            
            # Truncate tables to prevent unique constraint violations during restore
            cursor.execute("TRUNCATE TABLE message_embeddings CASCADE")
            cursor.execute("TRUNCATE TABLE messages CASCADE")
            cursor.execute("TRUNCATE TABLE sessions CASCADE")
            cursor.execute("TRUNCATE TABLE user_continuity CASCADE")
            
            print(f"Restoring {len(sessions)} sessions and {len(messages)} messages from {self.backup_file.name}...")
            
            # Restore sessions
            for sess in sessions:
                cursor.execute("""
                    INSERT INTO sessions (id, title, created_at, updated_at)
                    VALUES (%s, %s, %s, %s)
                """, (sess['id'], sess['title'], sess['created_at'], sess['updated_at']))

            # Restore messages
            for msg in messages:
                session_id = msg.get('session_id')
                # Optional: if migrating old backup, maybe generate a default session? 
                # Let's just insert it. If session_id is None, it should be fine if it's allowed, but foreign key requires session_id to exist or be NULL.
                # Actually, our schema allows NULL for session_id if it's not NOT NULL.
                cursor.execute("""
                    INSERT INTO messages (id, session_id, role, content, created_at, session_active, feedback)
                    VALUES (%s, %s, %s, %s, %s, %s, %s)
                """, (msg['id'], session_id, msg['role'], msg['content'], msg['created_at'], msg.get('session_active', 1), msg.get('feedback')))
            
            if messages:
                cursor.execute("SELECT setval(pg_get_serial_sequence('messages', 'id'), COALESCE(MAX(id), 1)) FROM messages")

            # Restore embeddings
            for emb in embeddings:
                cursor.execute("""
                    INSERT INTO message_embeddings (message_id, embedding, created_at)
                    VALUES (%s, %s::vector, %s)
                """, (emb['message_id'], emb['embedding'], emb['created_at']))

            # Restore user_continuity
            for item in continuity:
                cursor.execute("""
                    INSERT INTO user_continuity (identity, type, content, importance, priority, retired, created_at, last_updated)
                    VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
                """, (item['identity'], item['type'], item['content'], item['importance'], item['priority'], item['retired'], item['created_at'], item['last_updated']))
            
            conn.commit()
            cursor.close()
            conn.close()
            
            print("Successfully restored database from backup.")
            return True
            
        except Exception as e:
            print(f"Failed to restore from backup: {e}")
            return False
